### ISSUE TITLE
On which algorithm is the AGV Routing based 

### ISSUE THREAD

**Issue by SAMXYZ123** [rinde/RinSim#41]
Dear developer,

I would like to use your simulation for my bachelor-thesis in AGV routing. Is there an general definition of your algorithm? What is it based on?

Thanks in advance,
Nassim

**Comment by rinde** [comment]
Hi Nassim,

RinSim is not an algorithm, it is a simulator. Therefore, there is no routing algorithm nor are there plans to create one. I believe, however, that RinSim provides an ideal platform for developing multi-agent routing algorithms for AGVs.

The following paper may be of interest to you in this context: https://lirias.kuleuven.be/handle/123456789/541645

**Comment by SAMXYZ123** [comment]
Hi Rinde,

Thanks a lot for getting back to me. I am actually supposed to implement such an algorithm to make some test calculations with AGVs at the harbor of hamburg. Unfortunately my programming skills are not as good so I was hoping to find something that I would have to change only a little.

All the best,
Nassim
